baseURL = "https://mortenbarklund.com/"
languageCode = "en-us"
title = "Morten Barklund"
theme = "mediumish"
summaryLength = 25
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[params]
  logo = "/images/logo.svg"
  description = "Handy tips for writing better React."

[params.meta]
  description = "This website is your one-stop destination to handy tips for writing better React."
  keywords = "react, react hooks, react context, design patterns, react concurrent"

[params.author]
  name = "Morten Barklund"
  thumbnail = "/images/author.jpg"
  thumb = "/images/author.jpg"
  description = "Lead Frontend Developer, React expert, accessibility advocate, avid runner, and board game enthusiast. Also, I simply ❤️  corgis!"

[params.index]
  picture = "/images/logo.svg"
  title = "Morten Barklund"
  subtitle = "Handy tips for writing better React."
  recent = "Popular posts"

[params.social]
  github = "barklund"
  linkedin = "barklund"
  medium = "barklund"
  twitter = "barklund"
  instagram = "mbarklund"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "Book"
    weight = 100
    identifier = "book"
    url = "https://barklund.dev/rq2e"
[[menu.main]]
    name = "Subscribe"
    identifier = "Subscribe"
    weight = 200
    url = "/newsletter"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about"
[[menu.main]]
    name = "License"
    identifier = "license"
    weight = 300
    url = "/license"