name: Build and deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '42 15 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install webp
        run: sudo apt-get install webp

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.70.0"

      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: barklund/mortenbarklund.github.io
          publish_dir: ./public
          user_name: <barklund>
          user_email: <morten@barklund.dk>
          publish_branch: master
          cname: mortenbarklund.com