name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install wget
        run: sudo apt-get install wget
      - name: Download libwebp for linux
        run: wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0-linux-x86-64.tar.gz
      - name: Untar
        run: tar -xzf libwebp-1.1.0-linux-x86-64.tar.gz
      - name: Symlink cwebp
        run: sudo ln -s libwebp-1.1.0-linux-x86-64/bin/cwebp /usr/bin/cwebp
      - name: Test path
        run: echo $PATH
      - name: Test cwebp path
        run: which cwebp
      - name: Test cwebp
        run: cwebp --version

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.70.0"

      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: barklund/mortenbarklund.github.io
          publish_dir: ./public
          user_name: <barklund>
          user_email: <morten@barklund.dk>
          publish_branch: master
          cname: mortenbarklund.com